<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ti khon khng tn ti</name>
   <tag></tag>
   <elementGuidId>997ff8a2-b045-4b1e-91bf-2040ce7311d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notistack-snackbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notistack-snackbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>579db59d-082e-4473-b9d6-1b65588c5d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notistack-snackbar</value>
      <webElementGuid>4a132e8b-eb06-4a9e-a328-c138427342b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SnackbarItem-message</value>
      <webElementGuid>25293648-9626-4187-801f-9978d61fdd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>✖️Tài khoản không tồn tại</value>
      <webElementGuid>4ad89683-bcf3-4750-9968-73a6d980b190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notistack-snackbar&quot;)</value>
      <webElementGuid>651ca357-12c5-4716-a589-d6cbb5099a84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notistack-snackbar']</value>
      <webElementGuid>4ff5d4d5-af15-4222-8abd-b1a3e464f860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>5a04ddac-8a2b-4ccf-ab7c-7b92e2fd28ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo tài khoản mới'])[1]/following::div[7]</value>
      <webElementGuid>c9b8139c-0961-47fd-b5c9-d44171edf743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::div[8]</value>
      <webElementGuid>9c56f2a0-8c47-4924-aa7d-8e6e47deaa27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'notistack-snackbar', '&quot;', ')')])[1]/preceding::div[1]</value>
      <webElementGuid>87c84381-8999-4f52-894f-a85b56e076a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='✖️']/parent::*</value>
      <webElementGuid>583172bf-f233-444d-a79b-33012bdf98bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>c7d3b71f-adc5-4980-b3b2-737e2d0129ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'notistack-snackbar' and (text() = '✖️Tài khoản không tồn tại' or . = '✖️Tài khoản không tồn tại')]</value>
      <webElementGuid>40088ebf-7cdf-4167-b3a9-72688cd15735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
