<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Xem thm_MuiListItemIcon-root css-1f8bwsm</name>
   <tag></tag>
   <elementGuidId>cf5c2f26-da05-466c-904c-2ba120b21016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiListItemIcon-root.css-1f8bwsm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='joinRoomButton']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b17137e9-7180-4de5-b3ac-5650666dad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiListItemIcon-root css-1f8bwsm</value>
      <webElementGuid>bc392b3d-4a90-46ff-90f2-737e7c1a0a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;joinRoomButton&quot;)/div[@class=&quot;MuiListItemIcon-root css-1f8bwsm&quot;]</value>
      <webElementGuid>13d373a2-a6dc-4e11-ad3f-7e97a38f5ef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='joinRoomButton']/div</value>
      <webElementGuid>f6943c02-5a9d-4028-a226-8ed1d84f6e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem thêm'])[1]/following::div[7]</value>
      <webElementGuid>067ffd8f-e65b-4a37-acd0-381a99093a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[67]</value>
      <webElementGuid>6a268a6d-b7c6-4d24-9f7b-6c436e7ee0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>228d81ec-6e84-47b3-9ecc-1c7e4cec4781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
