<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hin_confirmpassword</name>
   <tag></tag>
   <elementGuidId>37eca150-d3e4-4b2e-bbbb-68b5e3006a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9d12076-18c6-473d-9b7d-45285e4b3931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e8a9cd4-34b1-49f7-a969-3b3a8db7e1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmpassword</value>
      <webElementGuid>7ed56d73-7056-4009-8dcc-3a96cf0661e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmpassword</value>
      <webElementGuid>fd6aafdf-b0ab-4e9a-a8c0-806c6b9b637e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Xác nhận mật khẩu...</value>
      <webElementGuid>01959fc1-e4b7-4e7e-80a2-5206069b7fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0aff6865-c024-49be-8e2c-b65657f12195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1x5jdmq</value>
      <webElementGuid>f8510524-b918-423c-acf4-4d1af6739a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmpassword&quot;)</value>
      <webElementGuid>54104e19-9216-411a-84a3-0c71122437ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmpassword']</value>
      <webElementGuid>4adf58f7-4cf5-43fd-a295-96a02a816496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>59ed06be-111a-4da9-b6a2-33853ebef950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>979a1f81-4828-440d-a8cb-2cdd286066d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmpassword' and @name = 'confirmpassword' and @placeholder = 'Xác nhận mật khẩu...' and @type = 'password']</value>
      <webElementGuid>ed8cdb52-b8be-4405-a690-5469164f25cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
