<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Vo phng</name>
   <tag></tag>
   <elementGuidId>29e049e2-678c-430d-8169-6efb93253f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#joinRoomButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='joinRoomButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>51793c6c-24f2-4d9e-9caf-fd35f6e03b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters css-1km1ehz</value>
      <webElementGuid>4a11d7c0-e13c-4148-958c-4a798c52fd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ed9adae2-2663-4ad5-8653-17208de291d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>7f2074c5-7af6-4bbe-ab12-52f79702d432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>joinRoomButton</value>
      <webElementGuid>166bd8f3-1648-4a9d-ab09-f437c4eff726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vào phòng</value>
      <webElementGuid>c988aa8b-a9c4-4ce4-b0f9-aa39a3557226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;joinRoomButton&quot;)</value>
      <webElementGuid>ef018f39-37e0-4755-9772-ad07b17ee889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='joinRoomButton']</value>
      <webElementGuid>b499f258-3c2d-4753-835c-77672310d590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'joinRoomButton', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>63e12c72-dacd-418d-ae90-8e2136a030ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem thêm'])[1]/following::li[1]</value>
      <webElementGuid>08dda09e-70a3-4529-bd62-a2ba2d2288d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>1158743a-3e52-456c-8b85-e76649569b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'joinRoomButton' and (text() = 'Vào phòng' or . = 'Vào phòng')]</value>
      <webElementGuid>49790055-ec28-412c-b7be-335b3fbfa24c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
