<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Email cant be empty</name>
   <tag></tag>
   <elementGuidId>9fd68f36-0e7b-46e6-816c-e9deb63b0a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='email-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>66afdf81-96ea-4a08-8c44-cce6e3488367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained Mui-required css-v7esy</value>
      <webElementGuid>c41afb64-5cde-40cd-bb93-f7b575df8a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-helper-text</value>
      <webElementGuid>cde6cb65-e1cb-43e7-81e4-597e2613a5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email can't be empty.</value>
      <webElementGuid>46cdccec-a103-4a0d-abe5-4e6be57e6ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-helper-text&quot;)</value>
      <webElementGuid>8d3db8d8-abe1-4e03-91fc-be703e818752</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='email-helper-text']</value>
      <webElementGuid>fb6446c2-1162-4ff1-93d1-0a98445a855c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div/div/p</value>
      <webElementGuid>b3d46b90-bf7e-432d-8d12-3f22ccf1c335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::p[1]</value>
      <webElementGuid>87f180e0-bfcf-4bf9-89bd-ab451fb55dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập vào tài khoản'])[1]/following::p[1]</value>
      <webElementGuid>3f9f6d8b-fece-4118-b075-27a3208ff41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::p[1]</value>
      <webElementGuid>e5699fac-5d90-46e5-92a6-1bfd6f9129e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiện'])[1]/preceding::p[1]</value>
      <webElementGuid>27c232f3-b0ea-4c2b-b253-7009228fd204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>05e7bc3f-4552-4efc-8d55-84cedad7a365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'email-helper-text' and (text() = concat(&quot;Email can&quot; , &quot;'&quot; , &quot;t be empty.&quot;) or . = concat(&quot;Email can&quot; , &quot;'&quot; , &quot;t be empty.&quot;))]</value>
      <webElementGuid>3f2b8120-5a10-48c8-86c3-b4d1ddb8cf18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
