<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Password cant be empty</name>
   <tag></tag>
   <elementGuidId>cc202edb-82c6-417e-a43d-29ed8f0c9775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='password-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>58d533fc-f3f0-4815-bd2a-bbdc07ec3f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained Mui-required css-v7esy</value>
      <webElementGuid>579051ae-c454-4d0c-98d1-1ff4666e5689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-helper-text</value>
      <webElementGuid>888e03ca-3947-4850-9eee-bbf60a1e18ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password can't be empty.</value>
      <webElementGuid>12212756-28a6-44b7-b2bd-b77f4f3797df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-helper-text&quot;)</value>
      <webElementGuid>55b3b88b-bd2e-445d-baaa-7bf4427435ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='password-helper-text']</value>
      <webElementGuid>3554ad57-c96f-4fa1-886f-2a27a9cb32d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div[2]/div/p</value>
      <webElementGuid>37f4d588-df8f-4576-96e3-51b09fc514f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/following::p[1]</value>
      <webElementGuid>fb4ffe05-6ee2-4c2b-acad-35149cde2861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::p[1]</value>
      <webElementGuid>ed1f5e42-7a50-4294-b696-b862a3190406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiện'])[1]/preceding::p[1]</value>
      <webElementGuid>74990b84-8eba-49fc-b07a-e0aea74538b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/preceding::p[1]</value>
      <webElementGuid>237e6069-0a41-474f-827b-2c2728bbfdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>107c230f-1808-46aa-9d0d-70d660e21125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'password-helper-text' and (text() = concat(&quot;Password can&quot; , &quot;'&quot; , &quot;t be empty.&quot;) or . = concat(&quot;Password can&quot; , &quot;'&quot; , &quot;t be empty.&quot;))]</value>
      <webElementGuid>ad55626c-1ca5-44f3-ba13-0a07d2ac70a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
