<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Xc nhn mt khu khng c  trng</name>
   <tag></tag>
   <elementGuidId>27f93b1d-2ced-4557-80ec-c9748afece3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmpassword-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='confirmpassword-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8574e712-24e9-46b6-b0f3-609a39607bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained Mui-required css-v7esy</value>
      <webElementGuid>ebc93417-d862-4ae6-bb85-3aa0e1c90871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmpassword-helper-text</value>
      <webElementGuid>7ae2ebb3-d751-4fba-81db-4fdd3ef80735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xác nhận mật khẩu không được để trống</value>
      <webElementGuid>0d2ff43b-6c77-4088-bfd1-616e2de5df74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmpassword-helper-text&quot;)</value>
      <webElementGuid>acda6def-480e-4e92-8c7c-f31b3ceb54a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='confirmpassword-helper-text']</value>
      <webElementGuid>d584a4b6-3503-4718-94e1-707a310cb6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div[3]/div/p</value>
      <webElementGuid>a91cdec4-9218-43db-95f7-360163f70ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/following::p[1]</value>
      <webElementGuid>0b1264fd-cd1d-40ce-8215-223a31880193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiện'])[1]/following::p[1]</value>
      <webElementGuid>1117cbe7-7a5b-4850-b1ab-e358a847c80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[2]/preceding::p[1]</value>
      <webElementGuid>b6786734-f6a3-42e8-8c6c-4351b473ace5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hoặc'])[1]/preceding::p[1]</value>
      <webElementGuid>96e74e09-5eda-4774-b638-5c63235b8efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xác nhận mật khẩu không được để trống']/parent::*</value>
      <webElementGuid>2873ebb7-fe8f-464d-96a0-f091c2c67918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>86b2d7e2-5a51-44e2-a5b9-e5c870357f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'confirmpassword-helper-text' and (text() = 'Xác nhận mật khẩu không được để trống' or . = 'Xác nhận mật khẩu không được để trống')]</value>
      <webElementGuid>abbc7e54-6591-4b70-926c-9f070947b965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
