<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Xc nhn mt khu khng trng khp vi mt khu</name>
   <tag></tag>
   <elementGuidId>743bdeca-7f9e-482c-b207-1b4f32d1dca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmpassword-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='confirmpassword-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e2a2ad6e-f99f-4d6b-a232-333345494157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained MuiFormHelperText-filled Mui-required css-v7esy</value>
      <webElementGuid>00beb771-d8b4-4cfb-b8c6-3768f238813b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmpassword-helper-text</value>
      <webElementGuid>2372b2f1-74fb-4392-a420-660819abba55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xác nhận mật khẩu không trùng khớp với mật khẩu</value>
      <webElementGuid>7b6ac86f-e4b8-4625-b2cb-bb66f72cee60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmpassword-helper-text&quot;)</value>
      <webElementGuid>b635b8a2-1469-42e3-a47f-92e684523a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='confirmpassword-helper-text']</value>
      <webElementGuid>463b201c-f448-44d0-8212-30b7a46704fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div[3]/div/p</value>
      <webElementGuid>d3b04883-6e47-44a7-b083-1f0556d34c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/following::p[1]</value>
      <webElementGuid>fde4b6bc-c621-4ee4-911e-81bcd7187633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiện'])[1]/following::p[1]</value>
      <webElementGuid>0d5cf667-cea9-45d0-90dd-75150d96de3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[2]/preceding::p[1]</value>
      <webElementGuid>f392904d-ee00-4885-95df-7d583eb6ff83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hoặc'])[1]/preceding::p[1]</value>
      <webElementGuid>7da9da95-01c6-41fb-9ef9-fc31ebc90c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xác nhận mật khẩu không trùng khớp với mật khẩu']/parent::*</value>
      <webElementGuid>9c73ecc8-eb3f-4ed0-87e9-3f013170dd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>44c62eba-c58c-4f4b-9e69-10a6a69e2a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'confirmpassword-helper-text' and (text() = 'Xác nhận mật khẩu không trùng khớp với mật khẩu' or . = 'Xác nhận mật khẩu không trùng khớp với mật khẩu')]</value>
      <webElementGuid>8a04a2fd-133a-4ad9-ae32-61e39bf00fe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
